resolver: lts-9.9
packages:
- cereal-conduit
- conduit
- conduit-extra
- network-conduit-tls
- resourcet
extra-deps:
- streaming-commons-0.1.17
- typed-process-0.2.0.0
- unliftio-core-0.1.1.0
- unliftio-0.2.4.0
- mono-traversable-1.0.8.1
- gauge-0.2.1
- basement-0.0.5
- foundation-0.0.18
nix:
  packages:
    - zlib
